pms/urls.py
    url(r'^manager/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'projects.views.project_manager', name='project_manager'),
    url(r'^managers/$','projects.views.managers_details',name='managers_details'),
    url(r'^project/view/(?P<id_disp>\d+)/$','projects.views.project_profile',name='project_profile'),
    url(r'^getprojects/$','projects.views.getprojects',name='getprojects'),
    url(r'^modules/$','projects.views.getmodules',name='modules_home'),
    url('^project/dashboard/(?P<id_disp>\d+)/$','projects.views.project_dashboard',name='project_dashboard'),
    #url(r'^tasks/view/(?P<id_disp>\d+)/$', 'projects.views.project_dashboard', name= 'task_with_no_assignees'),
    
    
    #----------------------------------PEOPLE----------------------------------------------#
    
    url(r'^person/(?P<task>(:?add))/$', 'people.views.people_details', name='people_details'),
    url(r'^persons/$','people.views.person_list',name='person_list'),
    url(r'^person/view/(?P<id_disp>\d+)/$','people.views.display_people',name='display_people'),
    url(r'^person/(?P<task>(:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','people.views.useredit',name='useredit'),
    url(r'^$','people.views.login_user',name='login_user'),
    url(r'^login/$','people.views.login_user',name='login_user'),
    url(r'^logout/$','people.views.logout_user',name='logout'),
    url(r'^person/add-user/(?P<unval>.*)/$', 'people.views.person_add', name = "person-add"),
    #url(r'^employers-home/$','people.views.employer_disp',name='employer_disp'),
    #url(r'^project/permission/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employee_details',name='employee_details'),
    #url(r'^employer/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employer',name='employer'),
    #url(r'^project/permissions/$','people.views.employees_list',name='employees_list'),
    #url(r'^person/add/$', 'people.views.add_user_for_client', name='add_user_for_client'),
    #url(r'^import/data/','people.views.import_data',name='import_data'),
    
    
    
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^task/add-document/(?P<tid>\d+)/$', 'documents.views.add_document', name='add-document'),
    url(r'^task/edit-document/(?P<tid>\d+)/$', 'documents.views.edit_document', name='edit-document'),
    url(r'^task/delete-document/(?P<tid>\d+)/$', 'documents.views.delete_document', name='delete-document'),
    url(r'^task/activate-document/(?P<tid>\d+)/$', 'documents.views.activate_document', name='activate-document'),
    url(r'^task/add/$', 'tasks.views.task_add', name='add'),
    url(r'^task/addmultiple/$', 'tasks.views.add_multiple_tasks', name='addm'),
    url(r'task/overdue/$','tasks.views.task_overdue',name='task_overdue'),
    url(r'^tasks/$','tasks.views.task_home', name='task'),
    url(r'^tasks/view/(?P<id_disp>\d+)/$','tasks.views.task_detail_view',name='detail'),
    url(r'^task/assigned/$','tasks.views.task_assigned',name='assign'),
    url(r'^task/ownedby/$','tasks.views.task_ownedby', name='task'),
    url(r'^task/following/$','tasks.views.task_following', name='task_following'),
    url(r'^gettasks/$','tasks.views.gettasks',name='gettasks'),
    url(r'^getmilestones/$','tasks.views.getmilestones',name='getmilestones'),
    url(r'^getmodules/$','tasks.views.getmodules',name='getmodules'),
    url(r'^getclients/$','projects.views.getclients',name='getclients'),
    url(r'^search/$', 'tasks.views.search', name='search'),
    url(r'^task/requests/$','tasks.views.task_requests', name='task_requests'),
    url(r'^task/request/add/$', 'tasks.views.task_request_add', name='task_request_add'),
    url(r'^task/request/view/(?P<id_disp>\d+)/$','tasks.views.task_request_view',name='task_request_view'),
    url(r'^task/edit/(?P<id_edit>\d+)/$','tasks.views.task_edit', name='edit'),
    url(r'^task/request/edit/(?P<id_edit>\d+)/$','tasks.views.task_request_edit', name='task_request_edit'),
    url(r'^task/assign/(?P<id_disp>[0-9]+)/$','tasks.views.add_task_request_to_new_task',name='add_task_request_to_new_task'),
    url(r'^task-commend/$', 'tasks.views.task_commend', name = "task-commend"),
    #    url(r'^deletetasks/(?P<id_delete>\d+)/$','documents.views.deletetasks', name='deletetasks'),
    url(r'^tasks/view/$', 'tasks.views.task_with_no_assignees', name= 'task_with_no_assignees' ),



    # url for milestones
    url(r'^milestone/view/(?P<id_disp>\d+)/$','milestones.views.view',name='view'),
    url(r'^milestones/$','milestones.views.mile', name='mile'),
    url(r'^milestones/view/(?P<id_disp>\d+)/$','milestones.views.milestone_view',name='milestone_view'),
    url(r'^milestones/(?P<task>(:?add|:?edit))/(?P<id>[0-9]+)/$', 'milestones.views.addmilestone', name='addmilestone'),
    url(r'^milestones/owned by me/$','milestones.views.milestone_owned_by', name='milestone_owned_by'),
    url(r'^milestones/deactive/(?P<id_delete>\d+)/$','milestones.views.deletemilestones',name='deletemilestones'),
    url(r'^milestones/active/(?P<id_active>\d+)/$','milestones.views.activemilestones',name='activemilestones'),
    url(r'^gettasks/$','milestones.views.gettasks',name='gettasks'),
    url(r'^getstatus/S','milestones.views.getstatus', name='getstatus'),
    url(r'^getmilestones/$','milestones.views.getmilestones',name='getmilestones'),
    url(r'^getpeople/$','milestones.views.getpeople',name='getpeople'),
    url(r'^milestones/import/$','milestones.views.import_data_m',name='import_data_m'), 
    #url(r'^milestones/documents/$','milestones.views.milestone_documents', name='milestone_documents'),
    #url(r'^addmilestonedocument/$', 'milestones.views.addmilestonedocument', name='addmilestonedocument'),
    #url(r'^editmilestonedocument/(?P<id_edit>\d+)/$','milestones.views.editmilestonedocument', name='editmilestonedocument'),
    url(r'^milestones/overdue/$','milestones.views.overdueview', name='overdueview'),
    url(r'^milestones/search/$', 'milestones.views.search', name='search'),
    url(r'^mile-comment/','milestones.views.milestone_comment', name="mile_comment"),
    url(r'^od/$','milestones.views.od',name='od'),





#---------------------------Times----------------------------------------#
    url(r'^times/$','times.views.tim', name='tim'),
    url(r'^addtimes/$', 'times.views.addtimes', name='addtimes'),
    url(r'^addmtimes/$', 'times.views.addmtimes', name='addmtimes'),
    url(r'^edittimes/(?P<id_edit>\d+)/$','times.views.edittimes', name='edittimes'),
    url(r'^time view/$','times.views.timeview',name='timeview'),
    url(r'^Weekly hour graph/$', 'times.views.whg', name='whg'),
    url(r'^times/manage/timesheets/(?P<task>(:?submit|:?approve|:?reject))/$','times.views.manage_time_sheets', name='manage_time_sheets'),
    url(r'^times/manage/timesheets/','times.views.manage_timesheets',name='manage_timesheets'),
    url(r'^Active timers/$', 'times.views.activetimer', name='activetimer'),
    url(r'^Missing timesheets/$', 'times.views.missingtime', name='missingtime'),
    url(r'^Submitted/$', 'times.views.sub', name='sub'),
    #url(r'^Manage time/(?P<id_submit>\d+)/$','times.views.current_week', name='current_week'),
    url(r'^Manage_time/$','times.views.current_week', name='current_week'),
    


#----------------mastermodule---------------------------
    url(r'^budgets/$','mastermodule.views.budget_details',name='budget_details'),
    url(r'^budget/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'mastermodule.views.budget', name='budget'),
    url(r'^task-stauses-home/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),
    url(r'^task-statuses/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.task_statuses',name='task_statuses'),
    url(r'^modules-home/$','mastermodule.views.modules_details',name='modules_details'),
    url(r'^modules/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.modules',name='modules'),
    url(r'^add settings/$', 'mastermodule.views.addsettings', name='addsettings'), 
    url(r'^Settings & Defaults/$','mastermodule.views.settings_and_defaults', name='settings_and_defaults'),
    url(r'^editsettings/(?P<id_edit>\d+)/$','mastermodule.views.editsettings', name='editsettings'),
    url(r'^settings/resource/categorization/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.resource_categorizations_details',name='resource_categorizations_details'),
    url(r'^settings/resource/categorizations/$','mastermodule.views.resource_categorization_list',name='resource_categorization_list'),
    url(r'^settings/project/categorization/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.project_categorization_details',name='project_categorizations_details'),
    url(r'^settings/project/categorizations/$','mastermodule.views.project_categorization_list',name='project_categorization_list'),
    url(r'^settings/task/priorities/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.task_priorities_details',name='task_priorities_details'),
    url(r'^settings/task/priorities/$','mastermodule.views.task_priorities_list',name='task_priorities_list'),
    url(r'^settings/statuses/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),
    url(r'^settings/statuses/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.task_statuses',name='task_statuses'),
    
    # --------------------Invoices ----------------------------------#
    url(r'^invoices-home/$','invoice.views.invoices_details',name='invoices_details'),
    url(r'^invoice/$','invoice.views.invoice_add',name='invoice_add'),
    url(r'^invoice_edit/(?P<id_edit>\d+)/$','invoice.views.invoice_edit',name='invoice_edit'),
    url(r'^invoice_delete/(?P<id_delete>\d+)/$','invoice.views.invoice_delete', name='invoice_delete'),
    url(r'^import/invoice/','invoice.views.import_data',name='import_data'),
)
    
#-------------Static files---------------------------------------#

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from projects.models import Project
from milestones.models import Milestone
from client.models import Client
from people.models import UserProfile
from mastermodule.models import Task_Statuses
from mastermodule.models import Task_priorities
from mastermodule.models import Modules
from django.db import IntegrityError
from django.utils.translation import gettext as _

MODULE = (('Design', 'Design'), ('Development', 'Development'), ('Discovery', 'Discovery'), ('Out of Scope', 
        'Out of Scope'), ('Production', 'Production'), ('Quality Assurance', 'Quality Assurance'))


STATUS = (('Open', 'Open'), ('Need', 'Need'), ('Assistance', 'Assistance'), ('Verify & Close', 'Verify & Close'), ('Reassign', 'Reassign'),
        ('Client Review', 'Client Review'), ('Closed', 'Closed'))

PRIORITY = (('Major', 'Major'), ('Showstopper', 'Showstopper'), ('Medium', 'Medium'), ('Low', 'Low'))


class Tasks(models.Model):
    title = models.TextField(max_length=100)
    client = models.ForeignKey(Client, blank=True, null=True)
    project = models.ForeignKey(Project)
    module = models.ForeignKey(Modules)
    start_date = models.DateField('Start Date')
    due_date = models.DateField('Due Date',blank=True, null=True)
    milestone = models.ForeignKey(Milestone, blank=True, null=True)
    status = models.ForeignKey(Task_Statuses)
    priority = models.ForeignKey(Task_priorities)
    owned_by = models.ManyToManyField(UserProfile, related_name='owned_by')
    assigned_to = models.ManyToManyField(UserProfile,related_name='assigned_by', blank=True, null=True)
    followed_by = models.ManyToManyField(UserProfile, related_name='followed_by', blank=True,null=True)
    estimated = models.FloatField(blank=True, null=True, default=None)
    actual = models.FloatField(blank=True, null=True, default=None)
    summary = models.TextField(max_length=100, blank=True, null=True)
    bug_reports = models.FileField(upload_to='static/bug reports', blank=True, null=True)

    def __unicode__(self):
        return self.title

    def get_total_actual(self):
        actual = 0
        same_date_list =  Tasks.objects.filter(start_date=self.start_date)
        for i in same_date_list:
            actual = float(actual)+float(i.actual)
        return actual

    def get_projects_list(self):
        projects = Project.objects.filter(project=self)
        return projects


    class Meta:
        ordering = ('title', )



class Request(models.Model):
    title = models.CharField(max_length=20)
    client = models.ForeignKey(Client)
    project = models.ForeignKey(Project)
    frm = models.ForeignKey(UserProfile, related_name='frm')
    priority = models.ForeignKey(Task_priorities)
    requested_due_date = models.DateField('Requested Due Date')
    description = models.TextField(max_length=100, blank=True, null=True)
    doc = models.FileField(upload_to='static/rdocuments', blank=True, null=True)


    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('title', )

times/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from projects.models import Project
from people.models import UserProfile
from tasks.models import Tasks
from client.models import Client
from mastermodule.models import Work_Type
from mastermodule.models import Modules

# Create your models here.


class AddTime(models.Model):
    person = models.ForeignKey(UserProfile)
    date = models.DateField(blank=True, null=True)
    times = models.FloatField(blank=True, null=True)
    client = models.ForeignKey(Client)
    project = models.ForeignKey(Project)
    module = models.ForeignKey(Modules)
    tasks = models.ForeignKey(Tasks, blank=True, null=True)
    worktype = models.ForeignKey(Work_Type)
    description = models.TextField(max_length=100, blank=True, null=True)
    billable = models.BooleanField()
    status_view = models.IntegerField(blank=True, null=True, default=0)

    def __unicode__(self):
        return self.tasks.title


    class Meta:
        ordering = ('times',)

tasks/forms.py
from django.db import models
from django import forms
from models import *




class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols':110,'rows':1}),required=True)
    status = forms.ModelChoiceField(queryset=Task_Statuses.objects.all(),initial='Open',widget=forms.Select(attrs={'data-rel':'chosen'}),)
    priority = forms.ModelChoiceField(queryset=Task_priorities.objects.all(),\
                                                    initial='Medium')
    assigned_to = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    owned_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),)
    followed_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(),empty_label='Choose a client',
                                                                required=False)
    module = forms.ModelChoiceField(queryset=Modules.objects.all(),
                                                    empty_label='Choose a module')
    milestone = forms.ModelChoiceField(queryset=Milestone.objects.all(),empty_label='Choose a Milestone',required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                                empty_label='Choose a project')
    summary     = forms.CharField(widget=forms.Textarea(attrs={'cols': 110, 'rows': 10}),required=False)
    bug_reports = forms.FileField(label='Upload a Document',required=False)
    
    
    
    class Meta:
        model = Tasks
        widgets = {
        'due_date': forms.DateInput(attrs={'class':'datepicker'}),
        'start_date': forms.DateInput(attrs={'class':'datepicker'}),
        }



class RequestForm(forms.ModelForm):



    class Meta:
        model = Request
        widgets = {
        'requested_due_date': forms.DateInput(attrs={'class':'datepicker'}),
        }

times/forms.py
from django.db import models
from django import forms
from times.models import *



class AddTimeForm(forms.ModelForm):
    person = forms.ModelChoiceField(queryset=UserProfile.objects.all(),
                                    empty_label='Choose a person')
    client = forms.ModelChoiceField(queryset=Client.objects.all(),
                                    empty_label='Choose a client',
                                    required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                    empty_label='Choose a project')
    module = forms.ModelChoiceField(queryset=Modules.objects.all(),
                                    empty_label='Choose a module')
    tasks = forms.ModelChoiceField(queryset=Tasks.objects.all(),
                                    empty_label='Choose a task')
    worktype = forms.ModelChoiceField(queryset=Work_Type.objects.all())
    

    class Meta:
        model = AddTime
        exclude = ('status_view',)
        widgets = {
        'pub_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }

templates/times/mtim.html
{% extends "main.html" %}
{% block midpart %}


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/static/resources/demos/style.css">

<script>
  $(function() {
    $(".datepicker" ).datepicker();
  });
  </script>

<script src="/static/js/jquery.validate.js"></script>

<script type="text/javascript">
$(document).ready(function(){


//$('#id_person').attr('data-rel','chosen');
$('#id_times').attr('class','form-control')
//$('#id_client').attr('data-rel','chosen');
//$('#id_project').attr('data-rel','chosen');
//$('#id_module').attr('data-rel','chosen');
//$('#id_tasks').attr('data-rel','chosen');
//$('#id_worktype').attr('data-rel','chosen');
//$('#id_description').attr('class','form-control')
//$('#id_pub_date').attr('class','form-control')











$("#times_form").validate({
rules :
{
title: {required: true},
client: {required: true},
project:{required: true},
worktype: {required: true},

},
});
});
</script>
<!--script to defualt due date -->
<script type="text/javascript">
    $( document ).ready(function() {
    for(i=0;i<=3;i++){
    $("#id_date").datepicker();
}
});
</script>

<!--script to set defualt owned by -->
<script>
$(document).ready(function(){
$('#id_owned_by').val({{user_id2.id}});
});
</script>
<script>
$(document).ready(function(){
$('#id_person').val({{user_id2.id}});
{% for i in tasks %}
$('#id_tasks').val({{i.id}})
{% endfor %}
//alert($('#id_owned_by').val({{user_id2.id}}))

})
</script>
<body>



<div class="row">
    <div class="box col-md-17">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Add Time</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
            <legend><h3>Add multiple time entries:</h3></legend>
            {% if error %} {{form.errors}} {% endif %}
       <form id = times_form class="form-inline" role="form" action="." method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                   <table class="table table-bordered table-striped table-condensed ">
                   <thead>
                   <tr>
                   <th>People</th>
                   <th>Date</th>
                   <th>Client</th>
                   <th>Project</th>
                   <th>Module</th>
                   <th>Task</th>
                   <th>Work type</th>
                   <th>Time</th>
                   </tr>
                   </thead>

                   <tr >
                   <td>{{form.person}}</td>
                   <td>{{form.date}}</td>
                   <td>{{form.client}}</td>
                   <td>{{form.project}}</td>
                   <td>{{form.module}}</td>
                   <td>{{form.tasks}}</td>
                   <td>{{form.worktype}}</td>
                   <td>{{form.time}}</td>
                   <td>{{form.description}}</td>
                   </tr>
                   <tr>
                   <td>{{subform.person}}</td>
                   <td>{{subform.date}}</td>
                   <td>{{subform.client}}</td>
                   <td>{{subform.project}}</td>
                   <td>{{subform.module}}</td>
                   <td>{{subform.tasks}}</td>
                   <td>{{subform.worktype}}</td>
                   <td>{{subform.time}}</td>
                   <td>{{subform.description}}</td>
                   </tr>
                   <tr>
                   
                   <td>{{subbform.person}}</td>
                   <td>{{subbform.date}}</td>
                   <td>{{subbform.client}}</td>
                   <td>{{subbform.project}}</td>
                   <td>{{subbform.module}}</td>
                   <td>{{subbform.tasks}}</td>
                   <td>{{subbform.worktype}}</td>
                   <td>{{subbform.time}}</td>
                   <td>{{subbform.description}}</td>
                   </tr>
                            
                            </table>
                <input type="submit" class="btn btn-default" value="Save" />
                            <a href="/times/" style="text-decoration:none;"> <button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                </>
    <!--/span-->
            
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->
</div>
</div>
{% endblock midpart %}

templates/times/tim.html
{% extends "main.html" %}
{% block midpart %}


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/static/resources/demos/style.css">

<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>
<script>
$(document).ready(function(){
$('#id_person').val({{user_id2.id}});
{% for i in tasks %}
$('#id_tasks').val({{i.id}})
{% endfor %}
//alert($('#id_owned_by').val({{user_id2.id}}))

})
</script>
<script src="/static/js/jquery.validate.js"></script>

<script type="text/javascript">
$(document).ready(function(){


//$('#id_person').attr('data-rel','chosen');
//$('#id_times').attr('class','form-control')
//$('#id_client').attr('data-rel','chosen');
//$('#id_project').attr('data-rel','chosen');
//$('#id_module').attr('data-rel','chosen');
//$('#id_tasks').attr('data-rel','chosen');
//$('#id_worktype').attr('data-rel','chosen');
//$('#id_description').attr('class','form-control')
//$('#id_pub_date').attr('class','form-control')











$("#milestone_form").validate({
rules :
{
title: {required: true},
project:{required: true},
worktype: {required: true},
},
});
});
</script>
<!--script to defualt due date -->
<script type="text/javascript" src="/static/js/jquery.datepick.js"> </script>
<!--link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"--> 
<script type="text/javascript">
$( document ).ready(function() {
$("#id_date").datepicker();
//$("#id_start_date").datepicker("setDate","{{today_date|date:'o/m/d'}}");
});
</script>

<!--script to set defualt owned by -->
<script>
$(document).ready(function(){
$('#id_owned_by').val({{user_id2.id}});
});
</script>
<script>
$( document ).ready(function() {
$('#id_client').change(function(){
    $('#id_project option').remove();
    var cid = $(this).val();
    $.ajax({
        type:'GET',
        url:'/getprojects/',
        data:{'cid':cid},
        success:function(data){
            if(data){
                var res = data.res;
                $('<option>',{value:''}).html('All Projects').appendTo('#id_project');
                for(i=0;i<res.length;i++)
                {
                    $('<option>',{value:res[i].id}).html(res[i].name).appendTo('#id_project');
                }
            }
        }
    })
    });
});
</script>

<body>



<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Add Time</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            {% if error %} {{form.errors}} {% endif %}
            <div class="box-content">
       <form id = times_form class="form-inline" role="form" action="." method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_person">Person:</label> <p>
                        {{form.person}}
                    </div>
                </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_date" >Date:</label> <p>
                        <!--<input id="id_pub_date" class="form-control" name="id_pub_date">-->
                        {{form.date}}
                    </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_time">Time:</label> <p>
                        <!--<input id="id_title" type="text" class="form-control" id="inputSuccess4" name="title">-->
                        {{form.times}}
                    </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_client">Client:</label> <p>
                        {{form.client}}
                    </div>
                </div>
                    <p>
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project">Project:</label> <p>
                        {{form.project}}
                    </div>
                </div>
                    <p>
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_module">Module:</label> <p>
                       {{form.module}}
                    </div>
                </div>
                    <p>
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_tasks">Task:</label> <p>
                       {{form.tasks}}
                    </div>
                </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_worktype">Worktype:</label> <p>
                       {{form.worktype}}
                    </div>
                </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label> <p>
                        <!--<input id="id_description" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                <p>
                <br>
                            <input type="submit" class="btn btn-default" value="Save" />
                            <a href="/times/" style="text-decoration:none;"> <button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                
    <!--/span-->
            
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->
</div>
</div>
{% endblock midpart %}