pms/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pms.views.home', name='home'),
    # url(r'^pms/', include('pms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
     
    url(r'^home/$','client.views.home',name='home'),
     
    url(r'^documents/', include('documents.urls')),
     # ---------------------------------Client----------------------------------------------#
    
    url(r'^client/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$', 'client.views.client_details', name='client_details'),
    url(r'^clients/$','client.views.client_list',name='client_list'),
    url(r'^client/view/(?P<id_disp>\d+)/$','client.views.display_client',name='display_client'),
    url(r'^import/data/','client.views.import_data',name='import_data'),
    url(r'^client/dashboard/(?P<id_disp>\d+)/$','client.views.dash_client',name='dash_client'),
    url('^recently/viewed/$','client.views.recently_viewed',name='recently_viewed'),
    
    # ---------------------------------Project---------------------------------------------#
    
    url(r'^project/(?P<task>(:?add))/$', 'projects.views.project_details', name='project_add'),
    url(r'^project/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$', 'projects.views.project_details', name='project_details'),
    url(r'^projects/$','projects.views.project_list',name='project_list'),
    url(r'^manager/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'projects.views.project_manager', name='project_manager'),
    url(r'^managers/$','projects.views.managers_details',name='managers_details'),
    url(r'^project/view/(?P<id_disp>\d+)/$','projects.views.project_profile',name='project_profile'),
    url(r'^getprojects/$','projects.views.getprojects',name='getprojects'),
    url(r'^modules/$','projects.views.getmodules',name='modules_home'),
    url('^project/dashboard/(?P<id_disp>\d+)/$','projects.views.project_dashboard',name='project_dashboard'),
    #url(r'^tasks/view/(?P<id_disp>\d+)/$', 'projects.views.project_dashboard', name= 'task_with_no_assignees'),
    
    
    #----------------------------------PEOPLE----------------------------------------------#
    
    url(r'^person/(?P<task>(:?add))/$', 'people.views.people_details', name='people_details'),
    url(r'^persons/$','people.views.person_list',name='person_list'),
    url(r'^person/view/(?P<id_disp>\d+)/$','people.views.display_people',name='display_people'),
    url(r'^person/(?P<task>(:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','people.views.useredit',name='useredit'),
    url(r'^$','people.views.login_user',name='login_user'),
    url(r'^login/$','people.views.login_user',name='login_user'),
    url(r'^logout/$','people.views.logout_user',name='logout'),
    url(r'^person/add-user/(?P<unval>.*)/$', 'people.views.person_add', name = "person-add"),
    #url(r'^employers-home/$','people.views.employer_disp',name='employer_disp'),
    #url(r'^project/permission/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employee_details',name='employee_details'),
    #url(r'^employer/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employer',name='employer'),
    #url(r'^project/permissions/$','people.views.employees_list',name='employees_list'),
    #url(r'^person/add/$', 'people.views.add_user_for_client', name='add_user_for_client'),
    #url(r'^import/data/','people.views.import_data',name='import_data'),
    
    
    
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^task/add-document/(?P<tid>\d+)/$', 'documents.views.add_document', name='add-document'),
    url(r'^task/edit-document/(?P<tid>\d+)/$', 'documents.views.edit_document', name='edit-document'),
    url(r'^task/delete-document/(?P<tid>\d+)/$', 'documents.views.delete_document', name='delete-document'),
    url(r'^task/activate-document/(?P<tid>\d+)/$', 'documents.views.activate_document', name='activate-document'),
    url(r'^task/add/$', 'tasks.views.task_add', name='add'),
    url(r'^task/addmultiple/$', 'tasks.views.add_multiple_tasks', name='addm'),
    url(r'task/overdue/$','tasks.views.task_overdue',name='task_overdue'),
    url(r'^tasks/$','tasks.views.task_home', name='task'),
    url(r'^tasks/view/(?P<id_disp>\d+)/$','tasks.views.task_detail_view',name='detail'),
    url(r'^task/assigned/$','tasks.views.task_assigned',name='assign'),
    url(r'^task/ownedby/$','tasks.views.task_ownedby', name='task'),
    url(r'^task/following/$','tasks.views.task_following', name='task_following'),
    url(r'^gettasks/$','tasks.views.gettasks',name='gettasks'),
    url(r'^getmilestones/$','tasks.views.getmilestones',name='getmilestones'),
    url(r'^getmodules/$','tasks.views.getmodules',name='getmodules'),
    url(r'^getclients/$','projects.views.getclients',name='getclients'),
    url(r'^search/$', 'tasks.views.search', name='search'),
    url(r'^task/requests/$','tasks.views.task_requests', name='task_requests'),
    url(r'^task/request/add/$', 'tasks.views.task_request_add', name='task_request_add'),
    url(r'^task/request/view/(?P<id_disp>\d+)/$','tasks.views.task_request_view',name='task_request_view'),
    url(r'^task/edit/(?P<id_edit>\d+)/$','tasks.views.task_edit', name='edit'),
    url(r'^task/request/edit/(?P<id_edit>\d+)/$','tasks.views.task_request_edit', name='task_request_edit'),
    url(r'^task/assign/(?P<id_disp>[0-9]+)/$','tasks.views.add_task_request_to_new_task',name='add_task_request_to_new_task'),
    url(r'^task-commend/$', 'tasks.views.task_commend', name = "task-commend"),
    #    url(r'^deletetasks/(?P<id_delete>\d+)/$','documents.views.deletetasks', name='deletetasks'),
    url(r'^tasks/view/$', 'tasks.views.task_with_no_assignees', name= 'task_with_no_assignees' ),



    # url for milestones
    url(r'^milestone/view/(?P<id_disp>\d+)/$','milestones.views.view',name='view'),
    url(r'^milestones/$','milestones.views.mile', name='mile'),
    url(r'^milestones/view/(?P<id_disp>\d+)/$','milestones.views.milestone_view',name='milestone_view'),
    url(r'^milestones/(?P<task>(:?add|:?edit))/(?P<id>[0-9]+)/$', 'milestones.views.addmilestone', name='addmilestone'),
    url(r'^milestones/owned by me/$','milestones.views.milestone_owned_by', name='milestone_owned_by'),
    url(r'^milestones/deactive/(?P<id_delete>\d+)/$','milestones.views.deletemilestones',name='deletemilestones'),
    url(r'^milestones/active/(?P<id_active>\d+)/$','milestones.views.activemilestones',name='activemilestones'),
    url(r'^gettasks/$','milestones.views.gettasks',name='gettasks'),
    url(r'^getstatus/S','milestones.views.getstatus', name='getstatus'),
    url(r'^getmilestones/$','milestones.views.getmilestones',name='getmilestones'),
    url(r'^getpeople/$','milestones.views.getpeople',name='getpeople'),
    url(r'^milestones/import/$','milestones.views.import_data_m',name='import_data_m'), 
    #url(r'^milestones/documents/$','milestones.views.milestone_documents', name='milestone_documents'),
    #url(r'^addmilestonedocument/$', 'milestones.views.addmilestonedocument', name='addmilestonedocument'),
    #url(r'^editmilestonedocument/(?P<id_edit>\d+)/$','milestones.views.editmilestonedocument', name='editmilestonedocument'),
    url(r'^milestones/overdue/$','milestones.views.overdueview', name='overdueview'),
    url(r'^milestones/search/$', 'milestones.views.search', name='search'),
    url(r'^mile-comment/','milestones.views.milestone_comment', name="mile_comment"),
    url(r'^od/$','milestones.views.od',name='od'),





#---------------------------Times----------------------------------------#
    url(r'^times/$','times.views.tim', name='tim'),
    url(r'^addtimes/$', 'times.views.addtimes', name='addtimes'),
    url(r'^addmtimes/$', 'times.views.addmtimes', name='addmtimes'),
    url(r'^edittimes/(?P<id_edit>\d+)/$','times.views.edittimes', name='edittimes'),
    url(r'^time view/$','times.views.timeview',name='timeview'),
    url(r'^Weekly hour graph/$', 'times.views.whg', name='whg'),
    url(r'^times/manage/timesheets/(?P<task>(:?submit|:?approve|:?reject))/$','times.views.manage_time_sheets', name='manage_time_sheets'),
    url(r'^times/manage/timesheets/','times.views.manage_timesheets',name='manage_timesheets'),
    url(r'^Active timers/$', 'times.views.activetimer', name='activetimer'),
    url(r'^Missing timesheets/$', 'times.views.missingtime', name='missingtime'),
    url(r'^Submitted/$', 'times.views.sub', name='sub'),
    #url(r'^Manage time/(?P<id_submit>\d+)/$','times.views.current_week', name='current_week'),
    url(r'^Manage_time/$','times.views.current_week', name='current_week'),
    


#----------------mastermodule---------------------------
    url(r'^budgets/$','mastermodule.views.budget_details',name='budget_details'),
    url(r'^budget/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'mastermodule.views.budget', name='budget'),
    url(r'^task-stauses-home/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),
    url(r'^task-statuses/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.task_statuses',name='task_statuses'),
    url(r'^modules-home/$','mastermodule.views.modules_details',name='modules_details'),
    url(r'^modules/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.modules',name='modules'),
    url(r'^add settings/$', 'mastermodule.views.addsettings', name='addsettings'), 
    url(r'^Settings & Defaults/$','mastermodule.views.settings_and_defaults', name='settings_and_defaults'),
    url(r'^editsettings/(?P<id_edit>\d+)/$','mastermodule.views.editsettings', name='editsettings'),

projects/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext as _
from django.contrib.contenttypes import generic
from people.models import *
from client.models import Client
from mastermodule.models import Work_Type

PROJECT_STATUS_TYPES = (('Maintenance','Mainteanace'),('Ongoing','Ongoing'),('Complete','Complete'))

class Project_Manager(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    from people.models import UserProfile
    userprofile = models.ForeignKey(UserProfile)

    def __unicode__(self):
        return self.userprofile.user.first_name

class Project(Base):
    client = models.ForeignKey(Client,blank=True,null=True)
    name = models.CharField(max_length=100)
    project_manager = models.ForeignKey(Project_Manager,blank=True,null=True)
    active = models.IntegerField(default=2)
    project_status = models.CharField(max_length=20,choices =PROJECT_STATUS_TYPES,blank=True,null=True)
    description = models.TextField(blank=True,null=True)
    billable = models.PositiveIntegerField(blank=True, null=True, default=2)
    start_date = models.DateField(blank = True, null = True)
    end_date = models.DateField(blank = True, null = True)
    budget = models.FloatField(default = None,blank=True,null=True)
    alert = models.FloatField(default = None,blank=True,null=True)
    
    def __unicode__(self):
        return self.name
    
    def get_user_profile(self):
        from projects.models import UserProfile
        people = UserProfile.objects.filter(project=self)
        return people
    def get_managers(self):
        managers = []
        for profile in self.get_user_profile():
            if profile.access_level == "Project Manager":
                managers.append(profile)
        return managers
    def get_users(self):
        from projects.models import UserProfile
        people = UserProfile.objects.get(project=self)
        return people
        
    def get_tasks_list(self):
        from tasks.models import Tasks
        task = Tasks.objects.filter(project=self)
        return task
        
    def get_milestones_list(self):
        from milestones.models import Milestone
        milestones = Milestone.objects.filter(project=self)
        return milestones
        
    def get_clients_list(self):
        clients_list = Client.objects.filter(project=self)
        return clients_list
        
    def get_modules(self):
        return Modules.objects.filter(content_type__name__iexact="project",object_id=self.id)
        
    def get_unclosed_task_list(self):
        from tasks.models import Tasks
        return Tasks.objects.filter(project=self).exclude(status__name='Closed')
        
    def get_no_assignee_task_list(self):
        from tasks.models import Tasks
        return Tasks.objects.filter(project=self,assigned_to=None)
        
class Project_Module_Relationship(Base):
    global_module = models.IntegerField(default=2)
    project = models.ForeignKey(Project,blank=True,null=True)
    content_type = models.ForeignKey(ContentType,
                                     verbose_name=_('content type'),
                                     related_name='Content_Type_Of_Modules')
    object_id = models.TextField(_('object ID'))
    
    
    def __unicode__(self):
        return self.project.name

client/forms.py
from django.forms import ModelForm
from client.models import Client
from django import forms

class ClientForm(forms.Form):
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea, required=False)
    address = forms.CharField(max_length=100, label='address', required = False)
    email = forms.EmailField(max_length=100, required=False)
    phone = forms.CharField(max_length=12, required=False)
    website = forms.URLField(max_length=100, required=False)
    fax = forms.CharField(max_length=20, required=False)

projects/forms.py
from django.forms import forms
from projects.models import *
from django import forms
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})



class ProjectForm(forms.Form):

    name            = forms.CharField()
    description     = forms.CharField(widget=forms.Textarea(attrs={'cols':110, 'rows':10}), required=False)
    project_status  = forms.ChoiceField(choices = PROJECT_STATUS_TYPES, \
                                                    widget=forms.Select(attrs={'data-rel':'chosen'}),
                                                    required=False)
    start_date      = forms.DateField(widget=DateInput("%Y-%m-%d"), required=False)
    end_date        = forms.DateField(widget=DateInput("%Y-%m-%d"), required=False)
    budget          = forms.FloatField(required=False)
    alert           = forms.FloatField(required=False)
    client          = forms.ModelChoiceField(queryset=Client.objects.all(), \
                                                widget=forms.Select(attrs={'data-rel':'chosen'}),
                                                required=False, empty_label="No Client")
    project_manager = forms.ModelChoiceField(queryset=Project_Manager.objects.all().order_by('name'), \
    
    required=False)
    
    
class Project_ManagerForm(forms.ModelForm):

    class Meta:
        model = Project_Manager
        

tasks/forms.py
from django.db import models
from django import forms
from models import *




class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols':110,'rows':1}),required=True)
    status = forms.ModelChoiceField(queryset=Task_Statuses.objects.all(),initial='Open',widget=forms.Select(attrs={'data-rel':'chosen'}),)
    priority = forms.ModelChoiceField(queryset=Task_priorities.objects.all(),\
                                                    initial='Medium')
    assigned_to = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    owned_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),)
    followed_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(),empty_label='Choose a client',
                                                                required=False)
    module = forms.ModelChoiceField(queryset=Modules.objects.all(),
                                                    empty_label='Choose a module')
    milestone = forms.ModelChoiceField(queryset=Milestone.objects.all(),empty_label='Choose a Milestone',required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                                empty_label='Choose a project')
    summary     = forms.CharField(widget=forms.Textarea(attrs={'cols': 110, 'rows': 10}),required=False)
    bug_reports = forms.FileField(label='Upload a Document',required=False)
    
    
    
    class Meta:
        model = Tasks
        widgets = {
        'due_date': forms.DateInput(attrs={'class':'datepicker'}),
        'start_date': forms.DateInput(attrs={'class':'datepicker'}),
        }



class RequestForm(forms.ModelForm):



    class Meta:
        model = Request
        widgets = {
        'requested_due_date': forms.DateInput(attrs={'class':'datepicker'}),
        }

templates/projects/index.html
{% extends "main.html" %}
{% block midpart %}
<div id="dashcontent">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Add New Designation</title>
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/component.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<script type="text/javascript"src="http://code.jquery.com/jquery-latest.js"></script>
<!-- <script type="text/javascript" src="js/jquery.peity.min.js"></script> -->
</head>
<body>
	<!--sitemap-->
	<div class="breadcrumbs">
		<a class="home" href="/home/">Home</a>
		<a href="designation.html">Designations</a><a href="newdesg.html">Manage</a><span>Add New</span>
            </div>
            <!-- main content -->
            <div class="maincontent">
                <h3>Project</h3>                  
                <div class="portlet box blue">
                    <div class="portlet-title"> Client </div>
                         <div id="employee-designation-grid" class="grid-view">
                                    {% if msg %}{{msg}}{% endif %}
                              <div>
                                 <form action ="." method = "POST" encrypte = "multipart/form-data" >{% csrf_token %}
                                            {{ form.as_p }}
                                    <input type="Submit" class="btnsubmit" value="submit" /> 
                                    <a href="/add/"> <button type="button">Cancel </button></a> 
                                  </form>
                                   
                              </div>
                       </div>
                  </div>
             </div>
</body>
</html>
</div>
{% endblock midpart %}

templates/projects/project.html
{% extends "main.html" %}
{% block midpart %}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>


<script src="/static/js/jquery.validate.js"></script>

<script type="text/javascript">
$(document).ready(function(){
$("#project_form").validate({
rules :
{
name: {required: true},
budget: {digits: true},
alert: {digits: true},
},
});
});



$(document).ready(function(){

$('#id_name').attr('class','form-control')
$('#id_description').attr('class','form-control')
$('#id_project_status').attr('class','form-control')
$('#id_budget').attr('class','form-control')
$('#id_alert').attr('class','form-control')
$('#id_project_manager').attr('class','form-control')
$('#id_client').attr('class','form-control')

})


</script>





<body>


<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Project Form</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
             {% if msg %}
                                     <font color="blue"><h3>{{msg}}</h3></font>
                                    {% endif %}
            {% if task == "add" %}
            <script>
$(document).ready(function() {
    //$('.datepicker').datepicker({dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true,"setDate":"{{today_date|date:'o/m/d'}}"}).attr( 'readOnly' , 'true' );
    $("#id_start_date").attr('value', "{{today_date|date:'o-m-d'}}");
    $('#id_end_date').attr("value","{{due_date|date:'o-m-d'}}");
});
</script>
<script type="text/javascript">
    
    $(document).ready(function(){
        {% if clientobj %}
            $('#id_client option').remove();
            var cid = {% if clientobj.id%}{{clientobj.id}}{%else%}0{%endif%}
            $('<option>', {value:cid}).html('{{clientobj.name}}').appendTo('#id_client');
            console.log("Client id======="+{{clientobj.id}});
        {% endif %}
    });
    
</script>
       <form id = "project_form" class="form-inline" role="form" action ="/project/add/0/" method="POST" enctype = "multipart/form-data" >{% csrf_token %}
       
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_client">Client:</label> <p>
                        {{form.client}}
                    </div>
                </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_name">Name:</label><p>
                        <!--<input id="id_description" type="text" class="form-control" name="name">-->
                        {{form.name}}
                    </div>
                    <p>
                    
                    
                       <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project_status">Project Status:</label> <p>
                        {{form.project_status}}
                    </div>
                </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label><p>
                        <!--<input id="id_phone" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_start_date">Start Date:</label><p>
                        <!--<input id="id_start_date" type="text" class="form-control" name="start_date">-->
                        {{form.start_date}}
                    </div>
                    <p>
                    
                       
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_end_date">End Date:</label><p>
                        <!--<input id="id_end_date" type="text" class="form-control" name="end_date">-->
                        {{form.end_date}}
                    </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_budget">Budget:</label><p>
                        <!--<input id="id_budget" type="text" class="form-control" name="budget">-->
                        {{form.budget}}
                    </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_alert">Alert:</label><p>
                        <!--<input id="id_alert" type="text" class="form-control" name="alert">-->
                        {{form.alert}}
                    </div>
                    <p>
                    
                       <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project_manager">Project Manger:</label> <p>
                        {{form.project_manager}}
                    </div>
                </div>
                    <p>
                    
                                <br>
                            <input type="submit" class="btn btn-default" value="Save" />
                             <a href="/projects/" style="text-decoration:none;"><button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                {% endif %}
    <!--/span-->
            
            <div class="box-content">
            {% if task == "edit" %}
            <script>
$(document).ready(function() {
    //$('.datepicker').datepicker({dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true}).attr( 'readOnly' , 'true' );
    $("#id_start_date").datepicker("setDate","{{today_date|date:'o/m/d'}}");
});
</script>
                    <form id="project_form" class="form-inline" role="form" action ="/project/edit/{{id_edit}}/" method = "POST" enctype = "multipart/form-data" >{% csrf_token %}
                         
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_client">Client:</label> <p>
                        {{form.client}}
                    </div>
                </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_name">Name:</label><p>
                        <!--<input id="id_description" type="text" class="form-control" name="name">-->
                        {{form.name}}
                    </div>
                    <p>
                    
                    
                       <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project_status">Project Status:</label> <p>
                        {{form.project_status}}
                    </div>
                </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label><p>
                        <!--<input id="id_phone" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_start_date">Start Date:</label><p>
                        <!--<input id="id_start_date" type="text" class="form-control" name="start_date">-->
                        {{form.start_date}}
                    </div>
                    <p>
                    
                       
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_end_date">End Date:</label><p>
                        <!--<input id="id_end_date" type="text" class="form-control" name="end_date">-->
                        {{form.end_date}}
                    </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_budget">Budget:</label><p>
                        <!--<input id="id_budget" type="text" class="form-control" name="budget">-->
                        {{form.budget}}
                    </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_alert">Alert:</label><p>
                        <!--<input id="id_alert" type="text" class="form-control" name="alert">-->
                        {{form.alert}}
                    </div>
                    <p>
                    
                       <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project_manager">Project Manger:</label> <p>
                        {{form.project_manager}}
                    </div>
                </div>
                    <p>
                <br>
                 <input type="submit" class="btn btn-default" value="Save" />
                             <a href="/projects/" style="text-decoration:none;"><button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->
</div>
</div>

</body>
</html>
</div>
{% endblock midpart %}