pms/urls.py
    url(r'^import/data/','client.views.import_data',name='import_data'),
    url(r'^client/dashboard/(?P<id_disp>\d+)/$','client.views.dash_client',name='dash_client'),
    url('^recently/viewed/$','client.views.recently_viewed',name='recently_viewed'),
    
    # ---------------------------------Project---------------------------------------------#
    
    url(r'^project/(?P<task>(:?add))/$', 'projects.views.project_details', name='project_add'),
    url(r'^project/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$', 'projects.views.project_details', name='project_details'),
    url(r'^projects/$','projects.views.project_list',name='project_list'),
    url(r'^manager/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'projects.views.project_manager', name='project_manager'),
    url(r'^managers/$','projects.views.managers_details',name='managers_details'),
    url(r'^project/view/(?P<id_disp>\d+)/$','projects.views.project_profile',name='project_profile'),
    url(r'^getprojects/$','projects.views.getprojects',name='getprojects'),
    url(r'^modules/$','projects.views.getmodules',name='modules_home'),
    url('^project/dashboard/(?P<id_disp>\d+)/$','projects.views.project_dashboard',name='project_dashboard'),
    #url(r'^tasks/view/(?P<id_disp>\d+)/$', 'projects.views.project_dashboard', name= 'task_with_no_assignees'),
    
    
    #----------------------------------PEOPLE----------------------------------------------#
    
    url(r'^person/(?P<task>(:?add))/$', 'people.views.people_details', name='people_details'),
    url(r'^persons/$','people.views.person_list',name='person_list'),
    url(r'^person/view/(?P<id_disp>\d+)/$','people.views.display_people',name='display_people'),
    url(r'^person/(?P<task>(:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','people.views.useredit',name='useredit'),
    url(r'^$','people.views.login_user',name='login_user'),
    url(r'^login/$','people.views.login_user',name='login_user'),
    url(r'^logout/$','people.views.logout_user',name='logout'),
    url(r'^person/add-user/(?P<unval>.*)/$', 'people.views.person_add', name = "person-add"),
    #url(r'^employers-home/$','people.views.employer_disp',name='employer_disp'),
    #url(r'^project/permission/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employee_details',name='employee_details'),
    #url(r'^employer/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employer',name='employer'),
    #url(r'^project/permissions/$','people.views.employees_list',name='employees_list'),
    #url(r'^person/add/$', 'people.views.add_user_for_client', name='add_user_for_client'),
    #url(r'^import/data/','people.views.import_data',name='import_data'),
    
    
    
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^task/add-document/(?P<tid>\d+)/$', 'documents.views.add_document', name='add-document'),
    url(r'^task/edit-document/(?P<tid>\d+)/$', 'documents.views.edit_document', name='edit-document'),
    url(r'^task/delete-document/(?P<tid>\d+)/$', 'documents.views.delete_document', name='delete-document'),
    url(r'^task/activate-document/(?P<tid>\d+)/$', 'documents.views.activate_document', name='activate-document'),
    url(r'^task/add/$', 'tasks.views.task_add', name='add'),
    url(r'^task/addmultiple/$', 'tasks.views.add_multiple_tasks', name='addm'),
    url(r'task/overdue/$','tasks.views.task_overdue',name='task_overdue'),
    url(r'^tasks/$','tasks.views.task_home', name='task'),
    url(r'^tasks/view/(?P<id_disp>\d+)/$','tasks.views.task_detail_view',name='detail'),
    url(r'^task/assigned/$','tasks.views.task_assigned',name='assign'),
    url(r'^task/ownedby/$','tasks.views.task_ownedby', name='task'),
    url(r'^task/following/$','tasks.views.task_following', name='task_following'),
    url(r'^gettasks/$','tasks.views.gettasks',name='gettasks'),
    url(r'^getmilestones/$','tasks.views.getmilestones',name='getmilestones'),
    url(r'^getmodules/$','tasks.views.getmodules',name='getmodules'),
    url(r'^getclients/$','projects.views.getclients',name='getclients'),
    url(r'^search/$', 'tasks.views.search', name='search'),
    url(r'^task/requests/$','tasks.views.task_requests', name='task_requests'),
    url(r'^task/request/add/$', 'tasks.views.task_request_add', name='task_request_add'),
    url(r'^task/request/view/(?P<id_disp>\d+)/$','tasks.views.task_request_view',name='task_request_view'),
    url(r'^task/edit/(?P<id_edit>\d+)/$','tasks.views.task_edit', name='edit'),
    url(r'^task/request/edit/(?P<id_edit>\d+)/$','tasks.views.task_request_edit', name='task_request_edit'),
    url(r'^task/assign/(?P<id_disp>[0-9]+)/$','tasks.views.add_task_request_to_new_task',name='add_task_request_to_new_task'),
    url(r'^task-commend/$', 'tasks.views.task_commend', name = "task-commend"),
    #    url(r'^deletetasks/(?P<id_delete>\d+)/$','documents.views.deletetasks', name='deletetasks'),
    url(r'^tasks/view/$', 'tasks.views.task_with_no_assignees', name= 'task_with_no_assignees' ),



    # url for milestones
    url(r'^milestone/view/(?P<id_disp>\d+)/$','milestones.views.view',name='view'),
    url(r'^milestones/$','milestones.views.mile', name='mile'),
    url(r'^milestones/view/(?P<id_disp>\d+)/$','milestones.views.milestone_view',name='milestone_view'),
    url(r'^milestones/(?P<task>(:?add|:?edit))/(?P<id>[0-9]+)/$', 'milestones.views.addmilestone', name='addmilestone'),
    url(r'^milestones/owned by me/$','milestones.views.milestone_owned_by', name='milestone_owned_by'),
    url(r'^milestones/deactive/(?P<id_delete>\d+)/$','milestones.views.deletemilestones',name='deletemilestones'),
    url(r'^milestones/active/(?P<id_active>\d+)/$','milestones.views.activemilestones',name='activemilestones'),
    url(r'^gettasks/$','milestones.views.gettasks',name='gettasks'),
    url(r'^getstatus/S','milestones.views.getstatus', name='getstatus'),
    url(r'^getmilestones/$','milestones.views.getmilestones',name='getmilestones'),
    url(r'^getpeople/$','milestones.views.getpeople',name='getpeople'),
    url(r'^milestones/import/$','milestones.views.import_data_m',name='import_data_m'), 
    #url(r'^milestones/documents/$','milestones.views.milestone_documents', name='milestone_documents'),
    #url(r'^addmilestonedocument/$', 'milestones.views.addmilestonedocument', name='addmilestonedocument'),
    #url(r'^editmilestonedocument/(?P<id_edit>\d+)/$','milestones.views.editmilestonedocument', name='editmilestonedocument'),
    url(r'^milestones/overdue/$','milestones.views.overdueview', name='overdueview'),
    url(r'^milestones/search/$', 'milestones.views.search', name='search'),
    url(r'^mile-comment/','milestones.views.milestone_comment', name="mile_comment"),
    url(r'^od/$','milestones.views.od',name='od'),





#---------------------------Times----------------------------------------#
    url(r'^times/$','times.views.tim', name='tim'),
    url(r'^addtimes/$', 'times.views.addtimes', name='addtimes'),
    url(r'^addmtimes/$', 'times.views.addmtimes', name='addmtimes'),
    url(r'^edittimes/(?P<id_edit>\d+)/$','times.views.edittimes', name='edittimes'),
    url(r'^time view/$','times.views.timeview',name='timeview'),
    url(r'^Weekly hour graph/$', 'times.views.whg', name='whg'),
    url(r'^times/manage/timesheets/(?P<task>(:?submit|:?approve|:?reject))/$','times.views.manage_time_sheets', name='manage_time_sheets'),
    url(r'^times/manage/timesheets/','times.views.manage_timesheets',name='manage_timesheets'),
    url(r'^Active timers/$', 'times.views.activetimer', name='activetimer'),
    url(r'^Missing timesheets/$', 'times.views.missingtime', name='missingtime'),
    url(r'^Submitted/$', 'times.views.sub', name='sub'),
    #url(r'^Manage time/(?P<id_submit>\d+)/$','times.views.current_week', name='current_week'),
    url(r'^Manage_time/$','times.views.current_week', name='current_week'),
    


#----------------mastermodule---------------------------
    url(r'^budgets/$','mastermodule.views.budget_details',name='budget_details'),
    url(r'^budget/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'mastermodule.views.budget', name='budget'),
    url(r'^task-stauses-home/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),
    url(r'^task-statuses/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.task_statuses',name='task_statuses'),
    url(r'^modules-home/$','mastermodule.views.modules_details',name='modules_details'),
    url(r'^modules/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.modules',name='modules'),
    url(r'^add settings/$', 'mastermodule.views.addsettings', name='addsettings'), 
    url(r'^Settings & Defaults/$','mastermodule.views.settings_and_defaults', name='settings_and_defaults'),
    url(r'^editsettings/(?P<id_edit>\d+)/$','mastermodule.views.editsettings', name='editsettings'),
    url(r'^settings/resource/categorization/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.resource_categorizations_details',name='resource_categorizations_details'),
    url(r'^settings/resource/categorizations/$','mastermodule.views.resource_categorization_list',name='resource_categorization_list'),
    url(r'^settings/project/categorization/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.project_categorization_details',name='project_categorizations_details'),
    url(r'^settings/project/categorizations/$','mastermodule.views.project_categorization_list',name='project_categorization_list'),
    url(r'^settings/task/priorities/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','mastermodule.views.task_priorities_details',name='task_priorities_details'),
    url(r'^settings/task/priorities/$','mastermodule.views.task_priorities_list',name='task_priorities_list'),
    url(r'^settings/statuses/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),

milestones/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from projects.models import Project
from people.models import UserProfile
from client.models import Client, Base
from django.db import IntegrityError

# Create your models here.

STATUS = (('In Progress', 'In Progress'),('Complete', 'Complete'))

class Milestone(Base):
    title = models.TextField(max_length = 100)
    client = models.ForeignKey('client.Client', blank=True, null=True, related_name='related_to_client')
    project = models.ForeignKey(Project)
    owned_by = models.ForeignKey(UserProfile, blank=True, null=True, related_name='related_to_owned_by')
    description = models.TextField(max_length=100, blank=True, null=True)
    due_date = models.DateField('Due Date', blank=True, null=True)
    #status = models.CharField(max_length=30,choices=STATUS, blank=True, null=True)
    status = models.BooleanField()
    available_task = models.ManyToManyField('tasks.Tasks', blank=True, null=True, related_name='related_to_advanced_milestone')
    activate = models.IntegerField(blank=True, null=True, default=2)

    def __unicode__(self):
        return self.title

    def get_task_actual_time(self):
        from tasks.models import Tasks
        actual_time = Tasks.objects.filter(milestone=self)
        return actual_time

    def get_task_actual(self):
        from tasks.models import Tasks
        actual = Tasks.objects.filter(milestone=self)
        return actual

    def get_userprofile(self):
        userprofile_list = UserProfile.objects.filter(milestone=self)
        return userprofile_list

    def get_tasks_list(self):
        task_list = Tasks.objects.filter(milestone=self)
        return task_list

    class Meta:
        ordering = ('title', )



class Milestone_Document(models.Model):
    milestone_documents = models.ForeignKey('milestones.Milestone', blank=True, null=True, related_name='related_to_milestone')
    files = models.ImageField(upload_to='static/milestone_documents', blank=True, null=True)
    title = models.CharField(max_length=100)
    tags = models.CharField(max_length=100)
    notes = models.TextField(blank=True, null=True)
    
    def __unicode__(self):
        return self.title

client/forms.py
from django.forms import ModelForm
from client.models import Client
from django import forms

class ClientForm(forms.Form):
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea, required=False)
    address = forms.CharField(max_length=100, label='address', required = False)
    email = forms.EmailField(max_length=100, required=False)
    phone = forms.CharField(max_length=12, required=False)
    website = forms.URLField(max_length=100, required=False)
    fax = forms.CharField(max_length=20, required=False)

milestones/forms.py
from django.db import models
from django import forms
from models import *




class MilestoneForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols':110,'rows':1}),required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'cols': 110, 'rows': 10}),required=False)
    YESNO_CHOICES = ((False, 'In Progress'), (True, 'Complete'))
    status = forms.ChoiceField(choices = YESNO_CHOICES, widget = forms.RadioSelect, initial='False')
    client = forms.ModelChoiceField(queryset=Client.objects.all(),\
                                   empty_label='Choose a client',\
                                   required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(),\
                                    empty_label='Choose a project')
    owned_by = forms.ModelChoiceField(queryset=UserProfile.objects.all(),\
                                    required=False)

    class Meta:
        model = Milestone
        exclude = ('activate',)
        widgets = {
        'due_date': forms.DateInput(attrs={'class':'datepicker'}),
        }


class Milestone_DocumentForm(forms.ModelForm):


    class Meta:
        model = Milestone_Document
        exclude = ('milestone_documents',)


#widget=forms.Select(attrs={'data-rel':'chosen'}),

people/forms.py
from django.forms import ModelForm
from people.models import *
from django import forms
from django.forms import widgets
from projects.models import *
import datetime
from django.utils.timezone import utc



class UserForm(forms.Form):
    title = forms.CharField(required=False,widget=forms.Select(choices=Title_choices))
    first_name = forms.CharField()
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    address = forms.CharField(widget=forms.Textarea(attrs={'cols': 30, 'rows': 5}),required=False)
    phone = forms.CharField(required=False)
    website = forms.URLField(required=False)
    network = forms.CharField(required=False)
    notes = forms.CharField(required=False)
    profile_image = forms.ImageField(label='Upload a Image',required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(),required=False)
    access_level = forms.CharField(max_length=30,widget=forms.Select(choices=Access_Level_CHOICES))
    project = forms.ModelMultipleChoiceField(queryset=Project.objects.all(),label='Project Permission',required=False)
    resource_categorization = forms.ModelChoiceField(queryset=Resource_Categorization.objects.all(),required=False)

    class Meta:
        model = UserProfile
        exclude = ('user','uuid')

class UserEditForm(forms.Form):
    title = forms.CharField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    address = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    website = forms.URLField(required=False)
    network = forms.CharField(required=False)
    notes = forms.CharField(required=False)
    profile_image = forms.ImageField(label='Profile Image',required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(),required=False)
    access_level   = forms.CharField(max_length=30,
                widget=forms.Select(choices=Access_Level_CHOICES))
    project = forms.ModelMultipleChoiceField(queryset=Project.objects.all(),label='Project Permission',required=False)
    resource_categorization = forms.ModelChoiceField(queryset=Resource_Categorization.objects.all(),required=False)
    class Meta:
        model = UserProfile
        exclude = ('user',)


class LoginForm(forms.Form):
    username = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    retypepassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        exclude = ('user',)
        widgets = {
            'password': forms.PasswordInput(),
            'retypepassword' : forms.PasswordInput(),
        }

    '''
class EmployeeForm(forms.Form):
    user = forms.ModelChoiceField(queryset=UserProfile.objects.all(),required=True)
    designation = forms.CharField(max_length=40,widget=forms.Select(choices=Designation_CHOICES))
    project_permission = forms.ModelMultipleChoiceField(queryset = Project.objects.all().order_by('name'),\
    required=False,widget=forms.CheckboxSelectMultiple)


class EmployerForm(forms.ModelForm):
    
    class Meta:
        model = Employer
    '''

templates/milestones/mile.html
{% extends "main.html" %}
{% block midpart %}



<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/static/resources/demos/style.css">

<link href="/static/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
<script src="/static/js/jquery.multi-select.js" type="text/javascript"></script>
<style>
.error{color:red; min-width: 200px;}
</style>


<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>

<script src="/static/js/jquery.validate.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$('#id_project').attr('data-rel','chosen');
$('#id_owned_by').attr('class','filter-select')
//$('#id_available_task').attr('class','filter-select')
$('#id_title').attr('class','form-control')
$('#id_description').attr('class','form-control')
$('#id_due_date').attr('class','form-control')
$('#id_fax').attr('class','form-control')
$('#id_status').attr('class','form-control')







$("#milestone_form").validate({
rules :
{


title: {required: true},
client:{required: true},
project:{required: true},
},
});

});
</script>
<script>
$(document).ready(function(){
   $('#my-select').multiSelect();
   $("#milestone_form").validate({
      rules: {
         title: {
            required: true
               }
         },
         messages: {
            title: "Required Field"
         }
         
         
         
         
     });
});

</script>


{% if task == "add" %}
<!--script to defualt due date -->
<script type="text/javascript">
$( document ).ready(function() {
$("#id_due_date").datepicker("setDate","{{todays|date:'m/d/o'}}");
});
</script>
{%endif%}



<!--script to set defualt owned by -->
<script>
$(document).ready(function(){
$('#id_owned_by').val({{user_id2.id}});
});
</script>

<script>
$( document ).ready(function() {
$('#id_client').change(function(){
    $('#id_project option').remove();
    var cid = $(this).val();
    
    $.ajax({
        type:'GET',
        url:'/getprojects/',
        data:{'cid':cid},
        success:function(data){
            if(data){
                var res = data.res;
                $('<option>',{value:''}).html('Select Project').appendTo('#id_project');
                for(i=0;i<res.length;i++)
                {
                    $('<option>',{value:res[i].id}).html(res[i].name).appendTo('#id_project');
                }
            }
        }
    })
    });
});
</script>


<body>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><span class="glyphicon glyphicon-edit"></span> Add Milestone</h2>

                <div class="box-icon">
                    <!--a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a-->
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
            {% if task == "add" %}
       <form id = milestone_form class="form-inline" role="form" action="/milestones/add/0/" method="POST">{% csrf_token %}
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_title">Title:</label> <p>
                        <!--<input id="id_title" type="text" class="form-control" id="inputSuccess4" name="title">-->
                        {{form.title}}
                    </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" >Client:</label> <p>
                        <!--select class="filter-select" name="client" id="id_client">
                        <option value = "">Select Client</option>
                        {% for a in client %}
                        <option value="{{a.id}}"> {{ a.name}} </option>
                                                    {% endfor %}
                                </select-->
                                {{form.client}}
                    </div>
                </div>
                    <p>
                    
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" >Project:</label> <p>
                       <!--select class="filter-select" name="project" id='id_project'>
                                    <option value = "">Select Project</option>
                                    {% for p in project %}
                                    <option value="{{p.id}}">{{p.name}}</option>
                                    {% endfor %}
                                </select-->
                        {{form.project}}
                    </div>
                </div>
                    <p>
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_owned_by">Owned By:</label> <p>
                       {{form.owned_by}}
                    </div>
                </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label> <p>
                        <!--<input id="id_description" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_due_date" >Due Date:</label> <p>
                        <!--<input id="id_due_date" class="form-control" name="id_due_date">-->
                        {{form.due_date}}
                    </div>
                    <p>
                    <div class="form-group has-success has-feedback">
                     <label class="control-label" for="id_status">Status:</label> <p>
                        {{form.status}}
                    </div>
                    <p>
    
                    <!--div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_available_task">Available Task:</label> <p>
                        {{form.available_task}}
                    </div>
                </div-->
                
                
                 <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_available_task">Available Task:</label> <p>
                    </div>
                </div>
              
                    <div id="my-select">
                     <select multiple="multiple" id="my-select" name="available_task">
                          <option value=''>{{form.available_task}}</option>
                    </select>
                </div>
                </p>
                <br>
                            <input type="submit" class="btn btn-default" value="Submit" />
                            <a href="/milestones/" style="text-decoration:none;"> <button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                {% endif %}
    <!--/span-->
                       
                            
            
            <div class="box-content">
            {% if task == "edit" %}
       <form id = milestone_form class="form-inline" role="form" action="/milestones/edit/{{id_edit}}/" method="POST">{% csrf_token %}
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_title">Title:</label> <p>
                        <!--<input id="id_title" type="text" class="form-control" id="inputSuccess4" name="title">-->
                        {{form.title}}
                    </div>
                    <p>
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_client">Client:</label> <p>
                        {{form.client}}
                    </div>
                </div>
                    <p>
                    
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project">Project:</label> <p>
                        {{form.project}}
                    </div>
                </div>
                    <p>
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_owned_by">Owned By:</label> <p>
                       {{form.owned_by}}
                    </div>
                </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label> <p>
                        <!--<input id="id_description" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                    <p>
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_due_date" >Due Date:</label> <p>
                        <!--<input id="id_due_date" class="form-control" name="id_due_date">-->
                        {{form.due_date}}
                    </div>
                    <p>
                    <div class="form-group has-success has-feedback">
                     <label class="control-label" for="id_status">Status:</label> <p>
                        {{form.status}}
                    </div>
                    <p>
                    
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_available_task">Available Task:</label> <p>
                    </div>
                </div>
                    
                    
                    <div id="my-select">
                     <select multiple="multiple" id="my-select" name="available_task">
                          <option value=''>{{form.available_task}}</option>
                    </select>
                </div>
                </p>
                <br>
                            <input type="submit" class="btn btn-default" value="Submit" />
                            <a href="/milestones/" style="text-decoration:none;"> <button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->
</div>
</div>
{% endblock midpart %}

templates/milestones/milestonedocument.html
{% extends "main.html" %}
{% block midpart %}


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>

<body>
	<!--sitemap
	<div class="breadcrumbs">
		<a class="home" href="main.html">Home</a>
		<a href="designation.html">PMS</a><a href="mile.html">Time</a><span>Add New</span>
            </div>-->
            <!-- main content -->
            <div class="maincontent">
                <h3>Milestone</h3>                  
                <div class="portlet box blue">
                         <div id="employee-designation-grid" class="breadcrumb">
                              <div>
                               <form action="." method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                                  {{ form.as_p }}
                                    <input type="submit" class="btnsubmit" value="Submit" />
                                    <a href="/milestones/" style="text-decoration:none;"> <button type ="button">Cancel</button> </a><br></br>
                                  </form><br>
                                    
                              </div>
                       </div>
                  </div>
             </div>
</body>
</html>
<div>





</div>
    </div>
    </div>

{% endblock midpart %}

templates/milestones/od.html
{{ due_dates}}
{{todays}}