pms/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pms.views.home', name='home'),
    # url(r'^pms/', include('pms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
     
    url(r'^home/$','client.views.home',name='home'),
     
    url(r'^documents/', include('documents.urls')),
     # ---------------------------------Client----------------------------------------------#
    
    url(r'^client/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$', 'client.views.client_details', name='client_details'),
    url(r'^clients/$','client.views.client_list',name='client_list'),
    url(r'^client/view/(?P<id_disp>\d+)/$','client.views.display_client',name='display_client'),
    url(r'^import/data/','client.views.import_data',name='import_data'),
    url(r'^client/dashboard/(?P<id_disp>\d+)/$','client.views.dash_client',name='dash_client'),
    url('^recently/viewed/$','client.views.recently_viewed',name='recently_viewed'),
    
    # ---------------------------------Project---------------------------------------------#
    
    url(r'^project/(?P<task>(:?add))/$', 'projects.views.project_details', name='project_add'),
    url(r'^project/(?P<task>(:?add|:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$', 'projects.views.project_details', name='project_details'),
    url(r'^projects/$','projects.views.project_list',name='project_list'),
    url(r'^manager/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'projects.views.project_manager', name='project_manager'),
    url(r'^managers/$','projects.views.managers_details',name='managers_details'),
    url(r'^project/view/(?P<id_disp>\d+)/$','projects.views.project_profile',name='project_profile'),
    url(r'^getprojects/$','projects.views.getprojects',name='getprojects'),
    url(r'^modules/$','projects.views.getmodules',name='modules_home'),
    url('^project/dashboard/(?P<id_disp>\d+)/$','projects.views.project_dashboard',name='project_dashboard'),
    #url(r'^tasks/view/(?P<id_disp>\d+)/$', 'projects.views.project_dashboard', name= 'task_with_no_assignees'),
    
    
    #----------------------------------PEOPLE----------------------------------------------#
    
    url(r'^person/(?P<task>(:?add))/$', 'people.views.people_details', name='people_details'),
    url(r'^persons/$','people.views.person_list',name='person_list'),
    url(r'^person/view/(?P<id_disp>\d+)/$','people.views.display_people',name='display_people'),
    url(r'^person/(?P<task>(:?edit|:?delete|:?active))/(?P<id>[0-9]+)/$','people.views.useredit',name='useredit'),
    url(r'^$','people.views.login_user',name='login_user'),
    url(r'^login/$','people.views.login_user',name='login_user'),
    url(r'^logout/$','people.views.logout_user',name='logout'),
    url(r'^person/add-user/(?P<unval>.*)/$', 'people.views.person_add', name = "person-add"),
    #url(r'^employers-home/$','people.views.employer_disp',name='employer_disp'),
    #url(r'^project/permission/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employee_details',name='employee_details'),
    #url(r'^employer/(?P<task>(:?add|:?edit|:?delete|:?active))/$','people.views.employer',name='employer'),
    #url(r'^project/permissions/$','people.views.employees_list',name='employees_list'),
    #url(r'^person/add/$', 'people.views.add_user_for_client', name='add_user_for_client'),
    #url(r'^import/data/','people.views.import_data',name='import_data'),
    
    
    
    
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^task/add-document/(?P<tid>\d+)/$', 'documents.views.add_document', name='add-document'),
    url(r'^task/edit-document/(?P<tid>\d+)/$', 'documents.views.edit_document', name='edit-document'),
    url(r'^task/delete-document/(?P<tid>\d+)/$', 'documents.views.delete_document', name='delete-document'),
    url(r'^task/activate-document/(?P<tid>\d+)/$', 'documents.views.activate_document', name='activate-document'),
    url(r'^task/add/$', 'tasks.views.task_add', name='add'),
    url(r'^task/addmultiple/$', 'tasks.views.add_multiple_tasks', name='addm'),
    url(r'task/overdue/$','tasks.views.task_overdue',name='task_overdue'),
    url(r'^tasks/$','tasks.views.task_home', name='task'),
    url(r'^tasks/view/(?P<id_disp>\d+)/$','tasks.views.task_detail_view',name='detail'),
    url(r'^task/assigned/$','tasks.views.task_assigned',name='assign'),
    url(r'^task/ownedby/$','tasks.views.task_ownedby', name='task'),
    url(r'^task/following/$','tasks.views.task_following', name='task_following'),
    url(r'^gettasks/$','tasks.views.gettasks',name='gettasks'),
    url(r'^getmilestones/$','tasks.views.getmilestones',name='getmilestones'),
    url(r'^getmodules/$','tasks.views.getmodules',name='getmodules'),
    url(r'^getclients/$','projects.views.getclients',name='getclients'),
    url(r'^search/$', 'tasks.views.search', name='search'),
    url(r'^task/requests/$','tasks.views.task_requests', name='task_requests'),
    url(r'^task/request/add/$', 'tasks.views.task_request_add', name='task_request_add'),
    url(r'^task/request/view/(?P<id_disp>\d+)/$','tasks.views.task_request_view',name='task_request_view'),
    url(r'^task/edit/(?P<id_edit>\d+)/$','tasks.views.task_edit', name='edit'),
    url(r'^task/request/edit/(?P<id_edit>\d+)/$','tasks.views.task_request_edit', name='task_request_edit'),
    url(r'^task/assign/(?P<id_disp>[0-9]+)/$','tasks.views.add_task_request_to_new_task',name='add_task_request_to_new_task'),
    url(r'^task-commend/$', 'tasks.views.task_commend', name = "task-commend"),
    #    url(r'^deletetasks/(?P<id_delete>\d+)/$','documents.views.deletetasks', name='deletetasks'),
    url(r'^tasks/view/$', 'tasks.views.task_with_no_assignees', name= 'task_with_no_assignees' ),



    # url for milestones
    url(r'^milestone/view/(?P<id_disp>\d+)/$','milestones.views.view',name='view'),
    url(r'^milestones/$','milestones.views.mile', name='mile'),
    url(r'^milestones/view/(?P<id_disp>\d+)/$','milestones.views.milestone_view',name='milestone_view'),
    url(r'^milestones/(?P<task>(:?add|:?edit))/(?P<id>[0-9]+)/$', 'milestones.views.addmilestone', name='addmilestone'),
    url(r'^milestones/owned by me/$','milestones.views.milestone_owned_by', name='milestone_owned_by'),
    url(r'^milestones/deactive/(?P<id_delete>\d+)/$','milestones.views.deletemilestones',name='deletemilestones'),
    url(r'^milestones/active/(?P<id_active>\d+)/$','milestones.views.activemilestones',name='activemilestones'),
    url(r'^gettasks/$','milestones.views.gettasks',name='gettasks'),
    url(r'^getstatus/S','milestones.views.getstatus', name='getstatus'),
    url(r'^getmilestones/$','milestones.views.getmilestones',name='getmilestones'),
    url(r'^getpeople/$','milestones.views.getpeople',name='getpeople'),
    url(r'^milestones/import/$','milestones.views.import_data_m',name='import_data_m'), 
    #url(r'^milestones/documents/$','milestones.views.milestone_documents', name='milestone_documents'),
    #url(r'^addmilestonedocument/$', 'milestones.views.addmilestonedocument', name='addmilestonedocument'),
    #url(r'^editmilestonedocument/(?P<id_edit>\d+)/$','milestones.views.editmilestonedocument', name='editmilestonedocument'),
    url(r'^milestones/overdue/$','milestones.views.overdueview', name='overdueview'),
    url(r'^milestones/search/$', 'milestones.views.search', name='search'),
    url(r'^mile-comment/','milestones.views.milestone_comment', name="mile_comment"),
    url(r'^od/$','milestones.views.od',name='od'),





#---------------------------Times----------------------------------------#
    url(r'^times/$','times.views.tim', name='tim'),
    url(r'^addtimes/$', 'times.views.addtimes', name='addtimes'),
    url(r'^addmtimes/$', 'times.views.addmtimes', name='addmtimes'),
    url(r'^edittimes/(?P<id_edit>\d+)/$','times.views.edittimes', name='edittimes'),
    url(r'^time view/$','times.views.timeview',name='timeview'),
    url(r'^Weekly hour graph/$', 'times.views.whg', name='whg'),
    url(r'^times/manage/timesheets/(?P<task>(:?submit|:?approve|:?reject))/$','times.views.manage_time_sheets', name='manage_time_sheets'),
    url(r'^times/manage/timesheets/','times.views.manage_timesheets',name='manage_timesheets'),
    url(r'^Active timers/$', 'times.views.activetimer', name='activetimer'),
    url(r'^Missing timesheets/$', 'times.views.missingtime', name='missingtime'),
    url(r'^Submitted/$', 'times.views.sub', name='sub'),
    #url(r'^Manage time/(?P<id_submit>\d+)/$','times.views.current_week', name='current_week'),
    url(r'^Manage_time/$','times.views.current_week', name='current_week'),
    


#----------------mastermodule---------------------------
    url(r'^budgets/$','mastermodule.views.budget_details',name='budget_details'),
    url(r'^budget/(?P<task>(:?add|:?edit|:?delete|:?active))/$', 'mastermodule.views.budget', name='budget'),
    url(r'^task-stauses-home/$','mastermodule.views.task_staus_details',name = 'task_staus_details'),
    url(r'^task-statuses/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.task_statuses',name='task_statuses'),
    url(r'^modules-home/$','mastermodule.views.modules_details',name='modules_details'),
    url(r'^modules/(?P<task>(:?add|:?edit|:?delete|:?active))/$','mastermodule.views.modules',name='modules'),
    url(r'^add settings/$', 'mastermodule.views.addsettings', name='addsettings'), 
    url(r'^Settings & Defaults/$','mastermodule.views.settings_and_defaults', name='settings_and_defaults'),
    url(r'^editsettings/(?P<id_edit>\d+)/$','mastermodule.views.editsettings', name='editsettings'),

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from projects.models import Project
from milestones.models import Milestone
from client.models import Client
from people.models import UserProfile
from mastermodule.models import Task_Statuses
from mastermodule.models import Task_priorities
from mastermodule.models import Modules
from django.db import IntegrityError
from django.utils.translation import gettext as _

MODULE = (('Design', 'Design'), ('Development', 'Development'), ('Discovery', 'Discovery'), ('Out of Scope', 
        'Out of Scope'), ('Production', 'Production'), ('Quality Assurance', 'Quality Assurance'))


STATUS = (('Open', 'Open'), ('Need', 'Need'), ('Assistance', 'Assistance'), ('Verify & Close', 'Verify & Close'), ('Reassign', 'Reassign'),
        ('Client Review', 'Client Review'), ('Closed', 'Closed'))

PRIORITY = (('Major', 'Major'), ('Showstopper', 'Showstopper'), ('Medium', 'Medium'), ('Low', 'Low'))


class Tasks(models.Model):
    title = models.TextField(max_length=100)
    client = models.ForeignKey(Client, blank=True, null=True)
    project = models.ForeignKey(Project)
    module = models.ForeignKey(Modules)
    start_date = models.DateField('Start Date')
    due_date = models.DateField('Due Date',blank=True, null=True)
    milestone = models.ForeignKey(Milestone, blank=True, null=True)
    status = models.ForeignKey(Task_Statuses)
    priority = models.ForeignKey(Task_priorities)
    owned_by = models.ManyToManyField(UserProfile, related_name='owned_by')
    assigned_to = models.ManyToManyField(UserProfile,related_name='assigned_by', blank=True, null=True)
    followed_by = models.ManyToManyField(UserProfile, related_name='followed_by', blank=True,null=True)
    estimated = models.FloatField(blank=True, null=True, default=None)
    actual = models.FloatField(blank=True, null=True, default=None)
    summary = models.TextField(max_length=100, blank=True, null=True)
    bug_reports = models.FileField(upload_to='static/bug reports', blank=True, null=True)

    def __unicode__(self):
        return self.title

    def get_total_actual(self):
        actual = 0
        same_date_list =  Tasks.objects.filter(start_date=self.start_date)
        for i in same_date_list:
            actual = float(actual)+float(i.actual)
        return actual

    def get_projects_list(self):
        projects = Project.objects.filter(project=self)
        return projects


    class Meta:
        ordering = ('title', )



class Request(models.Model):
    title = models.CharField(max_length=20)
    client = models.ForeignKey(Client)
    project = models.ForeignKey(Project)
    frm = models.ForeignKey(UserProfile, related_name='frm')
    priority = models.ForeignKey(Task_priorities)
    requested_due_date = models.DateField('Requested Due Date')
    description = models.TextField(max_length=100, blank=True, null=True)
    doc = models.FileField(upload_to='static/rdocuments', blank=True, null=True)


    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('title', )

tasks/forms.py
from django.db import models
from django import forms
from models import *




class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols':110,'rows':1}),required=True)
    status = forms.ModelChoiceField(queryset=Task_Statuses.objects.all(),initial='Open',widget=forms.Select(attrs={'data-rel':'chosen'}),)
    priority = forms.ModelChoiceField(queryset=Task_priorities.objects.all(),\
                                                    initial='Medium')
    assigned_to = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    owned_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),)
    followed_by = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                                                required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(),empty_label='Choose a client',
                                                                required=False)
    module = forms.ModelChoiceField(queryset=Modules.objects.all(),
                                                    empty_label='Choose a module')
    milestone = forms.ModelChoiceField(queryset=Milestone.objects.all(),empty_label='Choose a Milestone',required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                                empty_label='Choose a project')
    summary     = forms.CharField(widget=forms.Textarea(attrs={'cols': 110, 'rows': 10}),required=False)
    bug_reports = forms.FileField(label='Upload a Document',required=False)
    
    
    
    class Meta:
        model = Tasks
        widgets = {
        'due_date': forms.DateInput(attrs={'class':'datepicker'}),
        'start_date': forms.DateInput(attrs={'class':'datepicker'}),
        }



class RequestForm(forms.ModelForm):



    class Meta:
        model = Request
        widgets = {
        'requested_due_date': forms.DateInput(attrs={'class':'datepicker'}),
        }

templates/tasks/add-request.html
{% extends "main.html" %}
{% block midpart %}

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src="/static/js/jquery.validate.js"></script>


<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>

<script type="text/javascript">
$(document).ready(function(){
$("#request_form").validate({
rules :
{
title: {required: true},
},
});
});
</script>

<script>
$( document ).ready(function() {
$('#id_client').change(function(){
    $('#id_project option').remove();
    var cid = $(this).val();
    $.ajax({
        type:'GET',
        url:'/gettasks/',
        data:{'cid':cid},
        success:function(data){
            if(data){
                var res = data.res;
                $('<option>',{value:''}).html('All Projects').appendTo('#id_project');
                for(i=0;i<res.length;i++)
                {
                    $('<option>',{value:res[i].id}).html(res[i].name).appendTo('#id_project');
                }
            }
        }
    })
    });
});
</script>







<script type="text/javascript">
$(document).ready(function(){

//$('#id_client').attr('data-rel','chosen');
//$('#id_project').attr('data-rel','chosen');
//$('#id_frm').attr('data-rel','chosen');
//$('#id_priority').attr('data-rel','chosen');
//$('#id_doc').attr('class','form-control')
$('#id_title').attr('class','form-control')
$('#id_description').attr('class','form-control')
$('#id_requested_due_date').attr('class','form-control')

});
</script>


<script>
$(function() {
$( "#datepicker" ).datepicker();
$("#id_requested_due_date").datepicker("setDate","{{todays|date:'m/d/o'}}");

});
//$("#id_requested_due_date").datepicker("setDate","{{todays|date:'m/d/o'}}");

</script>

<body>



<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Task Request Form</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i
                            class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
                            class="glyphicon glyphicon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i
                            class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
<form id="request_form" class="form-inline" role="form" action="/task/request/add/" method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                    <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_title">Title:</label> <p>
                        <!--<input id="id_title" type="text" class="form-control" id="inputSuccess4" name="title">-->
                        {{form.title}}
                    </div>
                    <p>
                    
                    <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_client">Client:</label> <p>
                        {{form.client}}
                    </div>
                </div>
                    <p>
                    
                    
                      <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_project">Project:</label> <p>
                        {{form.project}}
                    </div>
                </div>
                    <p>
                    
                       <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_from">From:</label> <p>
                        {{form.frm}}
                    </div>
                </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                    <div class="controls">
                     <label class="control-label" for="id_priority">Priority:</label> <p>
                        {{form.priority}}
                    </div>
                </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_requested_due_date" >Requested Due Date:</label> <p>
                        <!--<input id="id_due_date" class="form-control" name="id_due_date">-->
                        {{form.requested_due_date}}
                    </div>
                    <p>
                    
                    
                     <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_description">Description:</label> <p>
                        <!--<input id="id_description" type="text" class="form-control" name="description">-->
                        {{form.description}}
                    </div>
                    <p>
                    
                  <div class="form-group has-success has-feedback">
                        <label class="control-label" for="id_doc">Upload a Document</label><p>
                        <!--input type="file" id="exampleInputFile"-->
                            {{form.doc}}
                    </div>
                    <p>
                
                <p>
                <br>
                            <input type="submit" class="btn btn-default" value="Save" />
                            <a href="/task/requests/" style="text-decoration:none;"> <button type="button" class="btn btn-default">Cancel</button> </a><br></br>
                </form>
    <!--/span-->
            
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->
</div>
</div>
{% endblock midpart %}

templates/tasks/add_task.html
{% extends "main.html" %}
{% block midpart %}




<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>




<body>
	<!--sitemap
	<div class="breadcrumbs">
		<a class="home" href="main.html">Home</a>
		<a href="designation.html">PMS</a><a href="tasks.html">Task</a><span>Add New</span>
            </div>-->
            <!-- main content -->
            <div class="maincontent">
                <h3>Task</h3>                  
                <div class="portlet box blue">
                         <div id="employee-designation-grid" class="breadcrumb">
                              <div>
                              {% if msg %}
                              {{ msg }}
                              {% endif %}
                                 <form action="." method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                                  {{ form.as_p }}
                                  
                                    
                                    <input type="submit" class="btnsubmit" value="Save task" />
                                     
                                     <input type="submit" value="Save task & create another" onclick="redirect();"/>
                                    <a href="/tasks/" style="text-decoration:none;"> <button type ="button">Cancel</button></a>
                                  </form>
                              </div>
                       </div>
                  </div>
             </div>
</body>
</html>



        </div>
    </div>


</div>

{% endblock midpart %}

templates/tasks/addm_task.html
{% extends "main.html" %}
{% block midpart %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script>
  $(function() {
    $( ".datepicker" ).datepicker();
  });
  </script>


<body>
	<!--sitemap
	<div class="breadcrumbs">
		<a class="home" href="main.html">Home</a>
		<a href="designation.html">PMS</a><a href="tasks.html">Task</a><span>Add New</span>
            </div>-->
            <!-- main content -->
            <div class="maincontent">
                <h3>Tasks</h3>                  
                <div class="portlet box blue">
                         <div id="employee-designation-grid" class="breadcrumb">
                              <div >
                                 <form action="." method="POST" enctype = "multipart/form-data" >{% csrf_token %}
                                  <h3> Task 1 : </h3>
                                  {{ form.as_p }}
                                  <h3> Task 2 : </h3>
                                  {{ subform.as_p }}
                                  <h3> Task 3 : </h3>
                                  {{ subbform.as_p }}
                                   <input type="submit" class="btnsubmit" value="Save task" />
                                   <a href="/tasks/" style="text-decoration:none;"><button type="button">Cancel</button> </a>
                                  </form>
                                  <br>
                                    <br></br>
                              </div>
                       </div>
                  </div>
             </div>
</body>
</html>
<div>



        </div>
    </div>


</div>

{% endblock midpart %}

templates/tasks/request.html
{% extends "main.html" %}
{% block midpart %}

<script>
function myFunction() {
    window.print();
}
</script>
            <!--sitemap-->
            <div class="breadcrumbs">
                   <!-- <a class="home" href="#">Home</a>-->
            </div>
                <!-- main content -->
                <!-- Work_Type -->
                    <div class="maincontent">
                        <div class="portlet box blue">
                         <div class="breadcrumb">
                         <li>
            <a href="/main/" style="text-decoration:none;">Home</a>
        </li>
        <li>
            <a href="/tasks/" style="text-decoration:none;">Task</a>
        </li>
                        </div>
                        {% if perms.tasks.add_request %}
                        <a class="breadcrumb" href="/task/request/add/" style="text-decoration:none;" >Add New Request</a>{% endif %}
                        <div id="employee-designation-grid" class="breadcrumb">
                        <h3>Request Queue  {{requests|length}} </h3>
                        <p>
                        <input id="" class="check" type="checkbox" onclick="" value="1">
                        <label for="f_summary">Show request description</label>
        <a title = "Print this Page" href="javascript:window.print()"><img src="/static/img/print-icon.png" height="25" width="25" align="right"></a>
                        </p>
                        <form>
                                <span class="sprites iconsPrintpage"></span>
                                </a>
                                </form>
                        <p>
                        <li>
                        <strong>Filter options:</strong>
                        <select>
                        <option value = "">All Clients</option>
                        {% for p in requests %}
                        <option value = "{{p.id}}">{{ p.client }}</option>
                        {% endfor %}
                        </select>
                        <select>
                        <option value = "">All Projects</option>
                        {% for p in requests %}
                        <option value = "{{p.id}}">{{ p.project }}</option>
                        {% endfor %}
                        </select>
                        <select>
                        <option value = "">All Requesters</option>
                        {% for p in requests %}
                        <option value = "{{p.id}}">{{ p.frm }}</option>
                        {% endfor %}
                        </select>
                        </li>
                        </p>
                        <br>
                                    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive" >
                                      {% if requests %}
                                          <thead>
                                                <tr>
                                                <th>#</th>
                                                <th>Title</th>
                                                <th>From</th>
                                                <th>Project</th>
                                                <th>Submitted</th>
                                                <th>Due_Date</th>
                                                <th>Assign as task</th>
                                                <th>Add to an existing task</th>
                                                {% if perms.tasks.change_request %}<th>Edit</th>{% endif %}
                                                <th>Select</th>
                                                </tr>
                                                       </thead>
                                            {% for p in requests %}
                                                <tr class="{% cycle 'odd' 'even'%}" align = "center">
                                                    <td>{{ p.id }}</td>
                                                    <td><a href="/task/request/view/{{p.id}}/" style="text-decoration:none;">{{ p.title }}</td></a>
                                                    <td>{{ p.frm}}</td>
                                                    <td>{{ p.project }}</td>
                                                    <td></td>
                                                    <td>{{ p.requested_due_date }}</td>
                                                    <td><a href="/task/assign/{{p.id}}" style="text-decoration:none;">new task</td>
                                                    {% if perms.tasks.change_request %}
                                                    <td><a href="#" style="text-decoration:none;">existing task</td>
                                                    {% endif %}
                                                    <td><a href="/task/request/edit/{{p.id}}/" class="glyphicon glyphicon-edit" ></a> </td>
                                                    <td><input type = checkbox ></td>
                                                </tr>
                                          {% endfor %}
                                      {% else %}
                                          <td style="text-align:center;color:blue;text-size:14px;">No Request added Yet...</td>
                                        {% endif %}
                                    </table>
                                    <div class="keys" style="display:none" title="">
                                    <span>3</span><span>2</span><span>1</span>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
    </div>
{% endblock midpart %}